// TodoList action types

export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const PATCH_TODO = 'PATCH_TODO';
export const PATCH_TODO_SUCCESS = 'PATCH_TODO_SUCCESS';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
export const DELETE_ALL_TODOS_SUCCESS = 'DELETE_ALL_TODOS_SUCCESS';
export const SET_PATCH_ON = 'SET_PATCH_ON';
export const SET_PATCH_OFF = 'SET_PATCH_OFF';
export const STOP_LOADER = 'STOP_LOADER';